INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 221, in inner
    if not self.has_permission(request):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 221, in inner
    if not self.has_permission(request):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /
ERROR:django.request:Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 221, in inner
    if not self.has_permission(request):
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/utils/functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 65, in __getitem__
    return self._session[key]
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rajaa/.local/share/virtualenvs/user_regist-r6GOr5cT/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
INFO:django.utils.autoreload:Watching for file changes with StatReloader
WARNING:django.request:Not Found: /
